# Generated by Django 3.2.8 on 2021-12-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('fkMember1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyapp.members')),
                ('fkMember2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='familyapp.members')),
                ('fkRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyapp.relation')),
            ],
        ),
    ]
