# Generated by Django 3.2.8 on 2021-12-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Childrens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkChild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyapp.members')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member11', to='familyapp.members')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='familyapp.members')),
            ],
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.AddField(
            model_name='childrens',
            name='fkParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyapp.parent'),
        ),
    ]
