# Generated by Django 3.2.8 on 2021-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0002_auto_20211207_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrens',
            name='gender',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
