# Generated by Django 3.2.8 on 2021-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0003_childrens_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.AddField(
            model_name='members',
            name='address',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
