# Generated by Django 3.2.8 on 2021-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyapp', '0004_auto_20211208_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrens',
            name='gender',
        ),
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
